### ISSUE TITLE
Problems of legend repaint and click

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#111]
I have 2 problems with the legend

Sometimes it does not redraw correctly:

![image](https://cloud.githubusercontent.com/assets/1484241/21395113/8c7597b6-c79b-11e6-9496-56ce85d85de3.png)

Also when we click on it the event is still not captured correctly and forwarded to the spectrum that makes a zoom

**Comment by NPellet** [comment]
Version ?

**Comment by NPellet** [comment]
So it is possible indeed. I don't keep track exactly when the legend has to be repainted and it's up to you to call graph.legendUpdate();

But I rather need to fix that.

**Comment by NPellet** [comment]
@lpatiny Can you try with 1.16.20 ? I changed the decision making triggering the automatic legend update. If it doesn't work, I'll have to look more into details in your application's behaviour

**Comment by lpatiny** [comment]
Currently I indeed don't have problems with legend not being paint but there is still the problem of the event not being catch by the legend and generates in our case a zoom.

**Comment by NPellet** [comment]
Cannot reproduce...

**Comment by lpatiny** [comment]
Concerning the click that is propagated I think it could be related to the mouseUp event that is not catch and therefore generates:

```
 graph.dom.addEventListener('mouseup', function (e) {

	    graph.emit("mouseUp", e);
	    //   e.preventDefault();
	    var coords = self._getXY(e);

	    _handleMouseUp(self, coords.x, coords.y, e);
	  });
```

@NPellet What do you think ?

**Comment by NPellet** [comment]
For a mouse up to occur, you need a mouse down to occur. And the mouse down is caught properly by the legend...

**Comment by lpatiny** [comment]
If I copy the line

	      this.rectBottom.addEventListener('mousedown', mousedown);

and add

	      this.rectBottom.addEventListener('mouseup', mousedown);
It works correctly.

**Comment by NPellet** [comment]
But then do you see the bug only when you mouse down outside the legend, drag into the legend, and mouse up inside the legend ?

**Comment by lpatiny** [comment]
No the bug is when I make a simple click in the legend. I don't move the mouse (at least not for purpose)

**Comment by NPellet** [comment]
Ok well I pushed a different patch that maybe fixes it. I'll let you check with 1.16.23

If it doesn't fix it I'll fix it on the mouse up but I still don't get it.

**Comment by lpatiny** [comment]
Seems ok !!!
