### ISSUE TITLE
Slots with dynamic jsGraph loading

### ISSUE THREAD

**Issue by NPellet** [NPellet/jsGraph#121]
Seems like the first print doesn't occur.
See NPellet/visualizer#1021 for more.

**Comment by lpatiny** [comment]
Is there a way to solve this problem ? Slots really improves a lot the performances ...

@targos Any comments that could help to solve this ?

**Comment by NPellet** [comment]
Before all I have to check with the latest version. Slots have changed.

I'll check that out tonight

**Comment by NPellet** [comment]
We should check this out with the new 2.0 version

**Comment by NPellet** [comment]
If this is ok now I'll close it. Reopen otherwise
