### ISSUE TITLE
Scatter serie points cannot get out of the drawing zone 

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#123]
Testcase: https://www.lactame.com/visualizer/HEAD/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/scatterSelect/view.json&dataURL=../testcase/data/scatterSelect/data.json

Try to pan the view using SHIFT + Drag. The points are somehow blocked and stay on the edges of the drawing zone

**Comment by NPellet** [comment]
That's a cool effect :D

**Comment by targos** [comment]
Yeah. Maybe you can keep it as an option ;)

**Comment by targos** [comment]
this is fixed
