### ISSUE TITLE
Status of the waveform branch

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#128]
@NPellet I'd like to make some refactorings but the waveform branch touches a lot of files.
Do you plan to merge it soon?

**Comment by NPellet** [comment]
No I will not merge it before April-May I think. At least that's the idea. The waveform branch is actually jsGraph 2.0. There are some breaking changes in the way the data is handled, and some bugs I corrected on the master branch but not on the waveform branch. But other than that, I think the branch is working. I think you'll want to work on that one.

**Comment by targos** [comment]
Just a heads up: I backported all the commits from master that weren't in waveform. I just excluded changes in `dist` and `web`.

**Comment by NPellet** [comment]
Ah that's really cool, thank you a lot. I was planning to merge the other way upon releasing version 2, but it's cool like that too.
