### ISSUE TITLE
Event problem in firefox and safari

### ISSUE THREAD

**Issue by stropitek** [NPellet/jsGraph#129]
### Steps to reproduce
- Go [here](https://www.lactame.com/visualizer/latest/index.html?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2Ffe007a221cc9f960895d9050e454ad92%2Fview.json)
- Click send to add annotations
- Zoom in with mouse click-drag-release
- Click send again, the annotations disappear

I looked into it and found out that the ui event callbacks are called differently on Chrome and Firefox. In Firefox, after a click-drag-release, the `click` callback is not called. This prevents `graph.prevent(false)` from being called and therefore `graph` stays in a "prevented" state where no annotations can be added (this prevented state is set by the zoom plugin).

**Comment by NPellet** [comment]
Ok, thanks.

Are we talking about the prevent(false) from the zoom plugin ? Can you tell me the line ?

**Comment by stropitek** [comment]
The zoom plugin sets the states to prevented [here](https://github.com/NPellet/jsGraph/blob/c17a454a4c3b85211ce8b00a757bf177e55f1c6a/src/plugins/graph.plugin.zoom.js#L253)
The click callback sets the state to not prevented [here](https://github.com/NPellet/jsGraph/blob/c17a454a4c3b85211ce8b00a757bf177e55f1c6a/src/graph.core.js#L2980)

**Comment by NPellet** [comment]
Hmmm you are right. The prevent(true) is to prevent the click event in chrome upon rezooming.
Any non-browser specific strategy ?

**Comment by targos** [comment]
Maybe try to prevent the click event from propagating when a drag occurs in the plugin?

**Comment by NPellet** [comment]
Wouldn't work, same DOM element that receives the event.

**Comment by stropitek** [comment]
On a different level, why is the creation of new annotations prevented entirely  ([here](https://github.com/NPellet/jsGraph/blob/master/src/graph.core.js#L1252-L1254)) when `prevent(true)` is called. I would guess that it should only prevent the creation of an annotation via the click event (which I think is already handled)

**Comment by NPellet** [comment]
No this is correct. That is the reason why the "beforeNewShape" event exists, to give the user a possibility to cancel shape creation.

**Comment by NPellet** [comment]
Maybe we can call prevent(false) preventively before these lines, to cancel any further prevents.

I could also review the whole system :D

**Comment by stropitek** [comment]
Just checked same bug in safari

**Comment by stropitek** [comment]
#133

**Comment by NPellet** [comment]
ok done
