### ISSUE TITLE
An option could prevent the selection of 2 spectra

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#147]
This would be kind of 'radio' button. When you select a spectrum and another one is already selected it is automatically unselected

**Comment by NPellet** [comment]
Actually jsgraph should not allow 2 spectra to be selected, ever

**Comment by lpatiny** [comment]
OK but if no spectra are selected then the vertical zoom still applies on all the spectra

**Comment by NPellet** [comment]
Actually what happens now is that when no spectra is selected, the zoom
applies to the axis.
When one is scaled, it's the xScale property of the waveform that is
affected. The docs is not ready but basically the waveforms can get an
offset a scale property for stretching.

2017-07-14 15:29 GMT+02:00 Luc Patiny <notifications@github.com>:
