### ISSUE TITLE
Unit tests are back!!!

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#190]
/cc @NPellet @lpatiny @stropitek 

Now that the library is developped with ES modules, I could migrate the tests to the jest test runner. This is a major improvement:

- Tests now work again
- We can test directly the source files (no need to transpile before)
- We can test any file individually
- Tests can use import syntax
- Tests are automatically executed in a simulated browser environment (jsdom)

I migrated the existing tests to https://github.com/NPellet/jsGraph/blob/master/src/__tests__/graph.js
To add new tests, just create test files in a `__tests__` directory next to the file that you want to test. As an example, I added https://github.com/NPellet/jsGraph/blob/master/src/__tests__/graph.util.js to test the `guid` function.

**Comment by targos** [comment]
It is also possible to generate a coverage report with `npm run test-coverage`

**Comment by NPellet** [comment]
Cool !
Thanks a lot.

Now I just need to create tests...  :D

Can we make some with some fake DOM library you think?

**Comment by stropitek** [comment]
> Can we make some with some fake DOM library you think?

Yes jest includes a fake dom library and was designed for testing the dom

**Comment by targos** [comment]
You have automatically access to `document` and `window` in the tests (thanks to jest and jsdom).

**Comment by targos** [comment]
I had to put the data_aggregator in a big `if` statement though because `URL.createObjectURL` is not supported by jsdom so this feature cannot be tested atm.

**Comment by targos** [comment]
Note that I also added a bunch of ESLint rules (by extending our common [cheminfo config](https://github.com/cheminfo/eslint-config)): https://github.com/NPellet/jsGraph/blob/master/.eslintrc.yml

I made sure it is compatible with the beautifier output, but I think we should aim to remove the beautifier and replace it with ESLint completely.
