### ISSUE TITLE
Webpack export default

### ISSUE THREAD

**Issue by NPellet** [NPellet/jsGraph#191]
Hey @targos 

I want to be able to call

import Graph from "node_modules/node-jsgraph/dist/jsgraph-es6.js" using the latest chrome version
But the current webpack configuration doesn't include an export default

Any idea ?

**Comment by targos** [comment]
It is not possible to do it without breaking current use case (`export` declarations are syntax errors if you don't import the file as a module). If you really want that, we need to do a 3rd version of the library in dist. I can work on that if you confirm that's what you want.

**Comment by NPellet** [comment]
Yes it is why I would like actually...  Just wondering if webpack had that
option

**Comment by NPellet** [comment]
Oh, ok. I'll check it out

2017-12-01 8:50 GMT+01:00 Michaël Zasso <notifications@github.com>:

**Comment by targos** [comment]
I added a module build. LMK if it works

**Comment by NPellet** [comment]
LGTM

Thanks !!
