### ISSUE TITLE
track data of chart of 1 point

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#192]
I have the case of a mass spectrum that contains only one peak.

If track is enable the mouse move seems to always return a null value.

**Comment by NPellet** [comment]
![image](https://user-images.githubusercontent.com/1484251/33476116-19cb85fe-d681-11e7-8f8e-10a91b5cddb6.png)

For me it seems to work...

**Comment by lpatiny** [comment]
But as far as I know xBefore and xAfter and the values on the xScale. What we would need is the index of the array for this value

**Comment by NPellet** [comment]
Old stuff. Reopen with an example if needed
