### ISSUE TITLE
rounding method is not used in waveform.getIndexFromData

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#194]
https://github.com/NPellet/jsGraph/blob/9c53a573b0174b55e745f425c31a8f67dc7c3ee4/src/util/waveform.js#L472-L486

**Comment by NPellet** [comment]
Binary search should return an int...

2017-12-01 10:38 GMT+01:00 Michaël Zasso <notifications@github.com>:

**Comment by targos** [comment]
so, this is a superfluous parameter?

**Comment by NPellet** [comment]
Yes you are right, it is :)

2017-12-11 13:54 GMT+01:00 Michaël Zasso <notifications@github.com>:
