### ISSUE TITLE
Any reason peak picking plugin is ignored by eslint ?

### ISSUE THREAD

**Issue by NPellet** [NPellet/jsGraph#195]

**Comment by targos** [comment]
https://github.com/NPellet/jsGraph/blob/7e0c331fc63e4283d37085dc7cad4187e1742531/.eslintignore#L3

**Comment by NPellet** [comment]
Oh sorry, that's Andres's code.

**Comment by NPellet** [comment]
( I thought it resolved to src/plugins/plugins.peakpicking.js )
