### ISSUE TITLE
box plots with duplicate X

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#210]
@jwist found a strange behavior.

It seems there is a bug in jsgraph when there is twice the same x values in boxplots:

```
{
  "title": "My chart",
  "data": [
    {
      "type": "box",
      "boxes":  [
        { "x": 0, "Q1": -1, "Q2": 2, "Q3": 5, "whiskers": [-5,10], "outliers": [  -7 ] },
        { "x": 0, "Q1": -1, "Q2": 2, "Q3": 5, "whiskers": [-5,10], "outliers": [  -7 ] },
        { "x": 1, "Q1": 5, "Q2": 7, "Q3": 15, "whiskers": [-3,16], "outliers": [ -5, 15 ] },
        { "x": 2, "Q1": 3, "Q2": 8, "Q3": 9, "whiskers": [1,11], "outliers": [ 0, -2, 12 ] },
        { "x": 3, "Q1": -2,"Q2": 1, "Q3": 3, "whiskers": [-4,6], "outliers": [ -6, 8 ] }
      ]
    }
  ]
}
``` 

renders like

![image](https://user-images.githubusercontent.com/1484241/43642588-83469cf4-9728-11e8-89d1-f4dcdfe2b12b.png)

While if I remove the duplicate X values I get:

![image](https://user-images.githubusercontent.com/1484241/43642607-909a7588-9728-11e8-9435-f8f2ac58e60c.png)

Is this normal ?

**Comment by NPellet** [comment]
Yes. It's perhaps not very elegant but the width of the bars is calculated using

```
  boxOtherDimension = Math.min( boxOtherDimension, Math.abs( axis2.getPx( this.data[ i + 1 ].pos ) - axis2.getPx( this.data[ i ].pos ) ) );
```

In this case, this.data[ i + 1 ] == this.data[ i ] hence the width is 0.
If you have any other idea as to how to calculate the box width I'm happy to implement it.

In the meantime I set a minimum of 5px, in 2.0.90

**Comment by NPellet** [comment]
For now we will not pursue further on this topic, unless there needs to be.
