### ISSUE TITLE
Display of peak picking is quite random when update data

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#212]
I have some problems with the integration of jsGraph in the visualizer

http://www.lactame.com/visualizer/HEAD/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/spectra_displayer/stacked/view.json&dataURL=../testcase/data/spectra_displayer/stacked/data.json

When we update the input variables the peak picking is sometimes (often) disappearing

The code we use for update based on the data is there: https://github.com/NPellet/visualizer/blob/master/src/modules/types/science/spectra/spectra_displayer/view.js#L625

I call this.graph.draw() after updating the data. Is this enough ?

**Comment by NPellet** [comment]
Closing. Reopen if still buggy on your side, with an example in the jsGraph repo
