### ISSUE TITLE
Zoom not working on documentation

### ISSUE THREAD

**Issue by bjonnh** [NPellet/jsGraph#218]
On http://jsgraph.org/tutorials/tutorial-10-zoom.html

When a users tries to zoom, it zoom on the wrong region.

Tested on the last dev version of Firefox and Chromium.

**Comment by NPellet** [comment]
Yes the website tutorials and examples are stuck the v1.6.

I've updated

http://jsgraph.org/tutorials/tutorial-10_basic.html
http://jsgraph.org/tutorials/tutorial-10-zoom.html

and the examples. The rest in WIP.
