### ISSUE TITLE
Preferences in json chart

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#222]
Related to #214 

JSON chart could contain some preferences information like:
* zoom horizontal, vertical, none, both
* scroll wheel function

For axis description:
* invert 
* from / to
* show major / minor grid

**Comment by targos** [comment]
I don't think user interaction should be set with json chart

**Comment by NPellet** [comment]
Agreed

**Comment by NPellet** [comment]
Check example /jsonAxes/style.json for some styling example

**Comment by NPellet** [comment]
(Visibility of the grid is toggled by 
 ```
       "primaryGrid": false,
        "secondaryGrid": false
```
)

**Comment by NPellet** [comment]
I added the options

"currentAxisMin" and "currentAxisMax" in the axes options. But not released yet. I might have broken some code (the beauty of not having unit tests...)

**Comment by NPellet** [comment]
And for the "invert", the option name is called "flipped"
