### ISSUE TITLE
Track 'vertical line'

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#224]
Currently the tracking mode finds the closest point on the line. In some case it would be nice to have the track line that is just the position of the vertical points at the mouse position.

Does this mode already exists ?

![cursor](https://user-images.githubusercontent.com/1484241/52166525-a4d5a100-270e-11e9-88cb-2ecea458f11b.gif)

**Comment by NPellet** [comment]
Yes now it's possible.

graph.getSerie('mySerie').options.tracking.useAxis = 'y'; (No API yet)

**Comment by lpatiny** [comment]
I can not find the option`useAxis`  in the source code

**Comment by NPellet** [comment]
I can confirm this works:

http://127.0.0.1:5500/examples/output/other/tracking_legend_useaxis.html
