### ISSUE TITLE
Zoom box fails if it goes from positive to negative vertical scale

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#225]
If I try a zoom box and my box goes from a positive Y to a negative Y the zoom will only be done on the X axis and not on the Y axis

![image](https://user-images.githubusercontent.com/1484241/53150248-69612080-35b0-11e9-9191-809096e90093.png)

![image](https://user-images.githubusercontent.com/1484241/53150323-9b728280-35b0-11e9-9157-b384dffeac0e.png)

![image](https://user-images.githubusercontent.com/1484241/53151011-55b6b980-35b2-11e9-815b-57a05c9e5e6e.png)

**Comment by NPellet** [comment]
The other way works ?

(For the legend we need to have a chat. Because I added it in the json
format)

Le jeu. 21 févr. 2019 à 08:26, Luc Patiny <notifications@github.com> a
écrit :

**Comment by targos** [comment]
It also fails with the X axis.

**Comment by NPellet** [comment]
Luc, do you have a test case for this ?

**Comment by lpatiny** [comment]
The last version solve this problem and it works perfectly now.

Thanks !
