### ISSUE TITLE
In from JSON allow in schema the plugins and mouseAction

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#226]
When creating a jsGraph object fromJSON could you copy from the schema
* mouseActions
* plugins

This would allow to have a rendered chart that can be interactive

**Comment by NPellet** [comment]
This is added in the latest commit, but not yet published.


I've actually added something that could be useful to you.

If you run ```grunt buildExamplesRenderer``` from the root repo it will look for all the json files in /examples/v2 and make a corresponding html file in /examples/output/ at the same file location. This way you can directly check the result.

**Comment by NPellet** [comment]
There's the /jsonPlugins folder where you can put your examples. Careful, this gets published to the website...
