### ISSUE TITLE
Zoom and markers problem

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#228]
When zooming into lines that have markers, the markers stay in place 

![image](https://user-images.githubusercontent.com/1484241/53295932-17193d00-3806-11e9-93c6-6669e2352186.png)

**Comment by NPellet** [comment]
I see your problem but I'm not experiencing it here. 

I need to be able to reproduce your example...

**Comment by lpatiny** [comment]
Here is an example in the visualizer

https://www.lactame.com/visualizer/src/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/spectra_displayer/multichart/view.json&dataURL=../testcase/data/spectra_displayer/multichart/data.json

I guess it could be related to the way we create the jsgraph instance and update the data if you can not reproduce it. Here is the related code:

https://github.com/NPellet/visualizer/blob/master/src/modules/types/science/spectra/spectra_displayer/view.js#L710-L901

**Comment by NPellet** [comment]
No, this should work out of the box.

I will be fixing it today. It's kind of important ;)

Le lun. 25 févr. 2019 à 07:48, Luc Patiny <notifications@github.com> a
écrit :

**Comment by NPellet** [comment]
Fixed and commited, but not released yet
