### ISSUE TITLE
Legend and selection of series

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#229]
The legend is now placed correctly thanks !

I still have a problem with selection of the series. If I click in the legend on one serie it is getting selected. But if I click again or click on another serie nothing happens.

**Comment by NPellet** [comment]
Yep I see it.

Le lun. 25 févr. 2019 à 07:18, Luc Patiny <notifications@github.com> a
écrit :

**Comment by NPellet** [comment]
Fixed
