### ISSUE TITLE
Line drawn outside the graph zone

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#230]
If you check the example

http://127.0.0.1:5500/examples/output/jsonPlugins/zoom.html

And zoom in

The bars are drawn also outside the chart area

![image](https://user-images.githubusercontent.com/1484241/53391182-d0f2e380-3995-11e9-8c55-c828a7cd3d99.png)

**Comment by NPellet** [comment]
Urgh

**Comment by NPellet** [comment]
Ok I commited a fix but didn't make a release yet.
