### ISSUE TITLE
example of high res mass spectrum of petrol

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#231]
I added an example: http://127.0.0.1:5500/examples/output/jsonLine/mass.html

With zoom in and vertical scale with scroll wheel.

@NPellet 

I have 2 questions: 
* why is the title not appearing ? (what I'm doing wrong)
* how we could add an event that would make a full zoom out like with the double click on shift click for example

![image](https://user-images.githubusercontent.com/1484241/53439046-755e3f80-3a01-11e9-98a7-abe19641bbfd.png)

**Comment by NPellet** [comment]
Add this: ``` { type: 'dblclick', plugin: 'zoom', shift: false, options: { mode: 'total' } }``` 

to the mouse actions

**Comment by lpatiny** [comment]
Thanks it works as expected !

**Comment by lpatiny** [comment]
Concerning the missing title in this example do you have any idea ? Is there an option to render the title on top of jsGraph ?

**Comment by NPellet** [comment]
options -> title

**Comment by NPellet** [comment]
But ok, since title will be quite common, you can now also add it at the top level.

So it's fixed

**Comment by lpatiny** [comment]
Great thanks !

**Comment by lpatiny** [comment]
And is there any way to customise the font and bold / italic ?

**Comment by NPellet** [comment]
No but it's a good idea. Open a separate ticket for that

**Comment by NPellet** [comment]
(btw, I published 2.1.14 with the fixes)
