### ISSUE TITLE
Gradual zoom out

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#232]
I added an example on:

http://127.0.0.1:5500/examples/output/jsonLine/mass.html

With gradual zoom out on SHIFT + double click

The first time it always work but if I shift double click many times it becomes erratic.

Could you have a look at it ?

**Comment by NPellet** [comment]
So far, I'm not observing this behavior. Can you elaborate / find maybe more reproducible steps to help ?

**Comment by lpatiny** [comment]
You tried with the example  that is in the project ?
1. zoom in
2. press SHIFT + double click
3. while you continuously maintain shift press make a second double click, third double click, etc

Many times (but the first time) the double click is missed at least on my computer with google chrome

**Comment by NPellet** [comment]
It is indeed possible that the event misses.
I think one issue may be if you do that while being on the serie. The event
is not bubbled anymore because it interferes with serie selection

Le mer. 27 févr. 2019 à 09:40, Luc Patiny <notifications@github.com> a
écrit :

**Comment by lpatiny** [comment]
You are completely right. I double click by mistake on a shape and therefore the event is catch. I think we may close this ticket.

**Comment by NPellet** [comment]
Not really. I think we should still be able to allow the double click.

Le mer. 27 févr. 2019 à 10:00, Luc Patiny <notifications@github.com> a
écrit :
