### ISSUE TITLE
Add styling possibilities for title

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#233]
Styling the title would be very useful to have publication quality charts

Probably color / bold / italic / font-family and size.

Should be this generalized to all the other text (axis value and axis description) ?

**Comment by NPellet** [comment]
So at the SVG level there is already font-family and size at the top level:

```
  util.setAttributeTo( this.dom, {
    'xmlns': Graph.ns,
    'font-family': this.options.fontFamily,
    'font-size': this.options.fontSize
  } );

```
But absolutely, we need to be able to have independent settings.
Color already exists for the axis value and axis label. I think it's in the API docs

**Comment by NPellet** [comment]
graph.setTitle("My graph title");
  graph.setTitleFontColor('green');
  graph.setTitleFontFamily('Consolas');
  graph.setTitleFontSize( 24 );


There we go !

**Comment by NPellet** [comment]
Also added the options { title: 'ABC', titleFontColor: '', titleFontFamily: '', titleFontSize: '' }
