### ISSUE TITLE
Change about tracking dot

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#234]
I have a problem between version 2.0 and 2.1 in which the tracking point is not visible anymore

Here is the result with 2.0

https://www.lactame.com/visualizer/v2.100.0/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/spectra_displayer/mouseTracking/view.json&dataURL=../testcase/data/spectra_displayer/mouseTracking/data.json

And with 2.1

https://www.lactame.com/visualizer/src/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/spectra_displayer/mouseTracking/view.json&dataURL=../testcase/data/spectra_displayer/mouseTracking/data.json

Just go over jsGraph to see the difference. Should we change something the module so that the tracking point is again visible ?

**Comment by lpatiny** [comment]
Is this bug solved in 2.1.15 ? Or there is now an option to let the track point appear ? I could not let it work.

**Comment by NPellet** [comment]
Don't know yet. Looking into it
