### ISSUE TITLE
synchronize 2 jsGraph

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#235]
I have a problem with the synchronization of 2 jsGraph (we would like that X and Y axis display the same values in both instance). We are using 2 events: zoom and zoomOutFull that allows to do nearly everything we need.

However the user may as well drag the chart and in this case the zoom event is not generated. Is there a way to know when the spectrum was dragged ?

**Comment by NPellet** [comment]
I think graph.getPlugin("drag").on("dragged", clbk)

Le jeu. 28 févr. 2019 à 11:22, Luc Patiny <notifications@github.com> a
écrit :

**Comment by NPellet** [comment]
Yes, you can register "dragging" and "dragged" onto the plugin
