### ISSUE TITLE
serie.setStyle is broken

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#238]
`this.styles` resolves to `undefined`

**Comment by NPellet** [comment]
Cannot be reproduced. Steps ?

**Comment by targos** [comment]
It happens with this example: http://www.lactame.com/visualizer/src/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/scatterSelect/view.json&dataURL=../testcase/data/scatterSelect/data.json

**Comment by NPellet** [comment]
It's because you cannot use .setStyle with the ScatterSerie.
However, as of 2.2.8, I added an alias from .setStyle( style, styleName) to .setMarkerStyle( style, undefined, styleName ). So you should be good.
