### ISSUE TITLE
handleMouseMove doesn't exist

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#239]
![image](https://user-images.githubusercontent.com/2352663/57836548-39957380-77c1-11e9-9c46-fccc244b15c8.png)

![image](https://user-images.githubusercontent.com/2352663/57836580-4ca84380-77c1-11e9-95e4-7bb3348344a6.png)

**Comment by NPellet** [comment]
Hmm yeah not anymore indeed. Looking into it

**Comment by NPellet** [comment]
New API:

var graph = new Graph( domGraph, { mouseMoveData: true } );

graph.on('mouseMoveData', ( results ) => {
    console.log( results );
});

You can also use a function directly in the options:  mouseMoveData: ( results ) => {}

Pushed in 2.2.2. Please let me know :)

**Comment by targos** [comment]
Thank you. This is mostly working but we don't get the MouseEvent object in the callback anymore. Is it possible to put it back?
