### ISSUE TITLE
display sec in minutes decimal format

### ISSUE THREAD

**Issue by dbehringer** [NPellet/jsGraph#241]
We are displaying in the X-axis of our GC viewer the time as min.sec using the parameter:
`unitModification: 'time:min.sec'`
150sec -> 2.30
165sec -> 2.45

is there another option to display the time in min.sec in decimal format like:
150sec -> 2.50
165sec -> 2.75

We don't want to change the data, but just the display...

Thanks for your help!

**Comment by NPellet** [comment]
Yes this can be done. I just have to see how

**Comment by dbehringer** [comment]
Hi Norman

I created a new unitPerTick case ('min') and solved this issue for our needs.
Not sure if this is the intended way to do for this project.

What would be the best way to contribute with my piece of code to the project?

**Comment by NPellet** [comment]
Oh cool that you did that. Just make a pull request, I'll merge it in,
build the project and publish it into a patch then :)

Thanks so much !

Le mer. 26 juin 2019 à 14:01, dbehringer <notifications@github.com> a
écrit :
