### ISSUE TITLE
track strange results

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#245]
Tracking is quite surprising if the curve contains a peak.

Check the bottom example on

https://www.lactame.com/visualizer/src/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/spectra_displayer/mouseTracking/view.json&dataURL=../testcase/data/spectra_displayer/mouseTracking/data.json

**Comment by NPellet** [comment]
That's what happens when you use the useAxis = 'y'

**Comment by lpatiny** [comment]
I did a break point in the code:
```
    findWithShortestDistance(options) {
      if (!options.axisRef) {
```
And `axisRef=false` so I didn't specify the 'y' axis. This behaviour seems to be the default one

![image](https://user-images.githubusercontent.com/1484241/60073325-6cb41680-9720-11e9-85fc-0af8668ecc40.png)

**Comment by NPellet** [comment]
axisRef is never defined with scatter plots.
It can however be defined with line plots.

Did you make sure of that ?

Le mar. 25 juin 2019 à 08:08, Luc Patiny <notifications@github.com> a
écrit :

**Comment by lpatiny** [comment]
I still have the problem with tracking.

https://www.lactame.com/visualizer/src/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/spectra_displayer/mouseTracking/view.json&dataURL=../testcase/data/spectra_displayer/mouseTracking/data.json

Here is the code when we add the tracking event.

https://github.com/NPellet/visualizer/blob/master/src/modules/types/science/spectra/spectra_displayer/view.js#L280-L290

**Comment by lpatiny** [comment]
While the default does not work correctly the tracking options is also not forwarded:

https://github.com/NPellet/jsGraph/blob/b67a29014f09de60ad50f3fc1024c9430d2d5877/src/graph.core.js#L3577

**Comment by NPellet** [comment]
Can you extract the dataset into an example ?

**Comment by lpatiny** [comment]
getClosestPointToXY is called twice in the code with different parameters:

As parameters it uses either:
* graph.options.mouseMoveDataOptions.useAxis
* serie.options.tracking.useAxis

@npellet Is this normal ?

```
            const closestPoint = serie.getClosestPointToXY(serie.getXAxis().getMouseVal(), serie.getYAxis().getMouseVal(), serie.options.tracking.withinPx, serie.options.tracking.withinPx, serie.options.tracking.useAxis, true); // When all legends are in common mode, let's make sure we remove the serie-specific legend
```

```
      for (let i = 0; i < graph.series.length; i++) {
        results[graph.series[i].getName()] = graph.series[i].getClosestPointToXY(undefined, undefined, graph.options.mouseMoveDataOptions.withinPxX || 0, graph.options.mouseMoveDataOptions.withinPxY || 0, graph.options.mouseMoveDataOptions.useAxis, true);
      }
```

**Comment by NPellet** [comment]
Ok I changed the code to 
```
  if ( graph.options.mouseMoveData ) {
    const results = {};

    for ( let i = 0; i < graph.series.length; i++ ) {

      if( ! serie.options.tracking ) {
        console.warn("Tracking not enabled for this serie");
        continue;
      }
      results[ graph.series[ i ].getName() ] = graph.series[ i ].getClosestPointToXY( 
        undefined, 
        undefined, 
        serie.options.tracking.withinPxX || 0, 
        serie.options.tracking.withinPxY || 0, 
        serie.options.tracking.useAxis, 
        true 
        );
    }
```

So now you need to use the tracking options to make the mouseMoveData even work.

**Comment by NPellet** [comment]
I'm not really sure where we are with this. Reopen a new ticket if you still get an issue with the tracking.
We should also document it
