### ISSUE TITLE
Array of label in annotations

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#246]
I'm using more and more array of labels in annotation and I think this feature has been removed.
```
 label:[
                {
                    text: fragment.comment,
                    position: {
                        x:fragment.ms.em,
                        dx: "2px",
                        y: "10px"
                    }
                },
                {
                    text: 'Z:'+fragment.ms.charge,
                    color:'grey',
                    position: {
                        x:fragment.ms.em,
                        dx: "2px",
                        y: "22px"
                    }
                },
            ],
```

**Comment by targos** [comment]
Just wondering: why was it not implemented as another kind of annotation?

**Comment by lpatiny** [comment]
Yes this would make the job ! Here is an example of the multiline annotation we do:
![image](https://user-images.githubusercontent.com/1484241/60099553-29759a00-9758-11e9-94f1-7844f4098e22.png)

**Comment by lpatiny** [comment]
It may still be interesting to have it related to an annotation in order to deal with the mouse over events. Currently you may go hover the text label or the annotation shape and it generates one event.

**Comment by NPellet** [comment]
> Just wondering: why was it not implemented as another kind of annotation?

To allow relative positioning and mouse interactions, as far as I remember. They are basically placed in the same SVG group

**Comment by NPellet** [comment]
Sorry for the verbosity...

```
 "labelText": [ "Boum", "Bam" ],
        "labelAngle": 30,
        "labelBaseline": "hanging",
        "labelSize": [ 14, 20 ],
        "labelColor": [ "green", "red" ],
        "labelAnchor": "middle",
        "labelBackgroundColor": "green",
        "labelBackgroundOpacity": 0.7,
        "labelPosition": [{ "x": 1, "y": 1, "dy": "-10px" }, {"x": 3, "y": 1, "dx": "30px", "dy": "-10px" }]
      }
```

As a reminder, these are exactly the way properties are stored in jsGraph, so there's not much flexibility. I directly feed the object into the shape. This also ensures that it remains maintainable over time...
