### ISSUE TITLE
getClosestPointToXY so to use the wrong coordinates

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#250]
I think getClosestPointToXY is using the coordinates of the spectrum and not the closest bases on pixels on the screen.

If the scale X is different from the scale Y this function returns non intuitive results.

**Comment by NPellet** [comment]
Actually I think it does.

axis.getMouseVal() returns the value in axis coordinate

**Comment by NPellet** [comment]
You need to enable useAxis: 'x' as well if you want x axis tracking. This is not the value by default
