### ISSUE TITLE
How to change font-size of axis ?

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#251]
I would need some way to be able to customize the chart from the renderer and in particular font-size of the labels, axis name and title.

I tried on:

https://www.lactame.com/visualizer/src/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/spectra_displayer/lineStyle/view.json&dataURL=../testcase/data/spectra_displayer/lineStyle/data.json

I tried to add:
```
  "options": {
    "fontSize": "20px"
  },
```

But I really get a strange result

![image](https://user-images.githubusercontent.com/1484241/65508700-1a29f800-ded1-11e9-922a-3adfb8daea74.png)

While the chart appears correctly otherwise 

![image](https://user-images.githubusercontent.com/1484241/65508736-2615ba00-ded1-11e9-87ff-58454ae489e4.png)

**Comment by NPellet** [comment]
It should be a number, because sometimes math is applied to it
