### ISSUE TITLE
Hiding spectrum does not grey the right icon

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#253]
When you hide a spectrum it is always the eye icon on the right that is grey out.

![image](https://user-images.githubusercontent.com/1484241/75602559-ca2a0f80-5ac6-11ea-976c-01fe5da3ebcd.png)

I tried here to click on the green eye but it was the blue that was hidden.

**Comment by NPellet** [comment]
Looks ok to me. Reopen if not
