### ISSUE TITLE
default annotation position

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#28]
For a annotation label, by default if no position is specified it would be nice to have "dx:0" and "dy:0".

Currently if no position is specified the label does not appear.

Test case:

http://www.cheminfo.org/?viewURL=http%3A%2F%2Fvisualizer.epfl.ch%2Fcheminfo%2Fb50564ac9d207212f8e5ae8167ca0b7a%2Fview.json%3Frev%3D8-833e716b626edc9c1e21d06833d90054

**Comment by NPellet** [comment]
644589a4ce41513edd292ca9f9fbcde4d2c6fe25
