### ISSUE TITLE
Peak picking algorithm could be improved ?

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#29]
The major peaks are not selected to show a label even if we zoom in the spectrum

http://www.cheminfo.org/?v=v2.9.10&viewURL=http%3A%2F%2Fvisualizer.epfl.ch%2Fcheminfo%2Fb50564ac9d207212f8e5ae8167ec22a5%2Fview.json%3Frev%3D4-f040ee9cb45a7ba60ae01b1c6895ddab

**Comment by NPellet** [comment]
It's because they're out of the y zoom range. It's feature to see the smaller peaks.
I added an option to display also the peaks about the maximum y value.

http://jsgraph.org/examples/others/peakpicking-discrete.js/
