### ISSUE TITLE
Marker events are not always fired

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#32]
We have a problem @NPellet 

When two markers are close enough to each other that they overlap, some mouse events are missing : 
If the mouse enters marker1, goes over it to marker2 and leaves marker2, only 2 events are fired : 
1. mouse over (marker 1)
2. mouse out (marker 2)

This is because the markers are all part of the same DOM element.

**Comment by NPellet** [comment]
Yes I noticed that a long time ago.
No real way to fix that except giving one marker its own dom... Which I 
would only do as an option

**Comment by NPellet** [comment]
Try
```
markersIndependant: true 
```
in the serie option with the latest commit 0ca3457753af72e575051c92148c6df0697befba

I haven't checked all the features.

**Comment by NPellet** [comment]
Any news on that ?

**Comment by targos** [comment]
There is a problem with the `toggleMarker` method.
Here is a simple testcase: https://gist.github.com/targos/bb05a4c7a77e02ec2876

Try hovering the markers to see the error
If you comment out the `markersIndependant: true` line, there is no problem.

**Comment by targos** [comment]
Easier to test: http://jsfiddle.net/080mdc79/

**Comment by NPellet** [comment]
Ok, thanks for letting me know. I will look into it ASAP.

**Comment by NPellet** [comment]
Fixed with v1.11.2
Speed should also be greatly enhanced for most graphs with zoom and without slots or xIsMonotoneous.

**Comment by targos** [comment]
perfect, thanks !
