### ISSUE TITLE
Give the possibility for event over peak picking

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#33]
I would like to be able that when a user goes over or click on a peak picking label there is an action that is executed.

In practice what I would like is that when you click on the label, ChemCalc with try to find the possible molecular formula that could fit a monoisotopic mass and then superimpose the predicted spectrum.

The missing part is the possibility to have a callback on the label click. I could use the mouse tracking event but I don't think it would be as accurate.

**Comment by NPellet** [comment]
It already exists. Peak pickings are regular shapes.

```Javascript
graph.on("shapeSelect", function( shape ) {

});

graph.on("shapeUnselect", function( shape ) {

});

See GCMS code for more example.
