### ISSUE TITLE
Find a general way to check for arrays

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#40]
Example of problematic place: https://github.com/NPellet/jsGraph/blob/master/src/graph._serie.js#L63-L77
`instanceof` doesn't work for Typed arrays ! Neither does `Array.isArray`.
Perhaps we can use something like
```js
function isArray(value) {
  return typeof value === 'object' && typeof value.length === 'number'
}
```

**Comment by NPellet** [comment]
But at this stage, they shouldn't be typed arrays, right ?

So is it a special application of yours that feeds Typed arrays to jsGraph ?

2015-07-03 15:05 GMT+08:00 Michaël Zasso <notifications@github.com>:

**Comment by lpatiny** [comment]
A way to check an array is to do:
```
Object.prototype.toString.call([])
"[object Array]"
Object.prototype.toString.call(new Uint16Array())
"[object Uint16Array]"
```
A indexOf the resulting string for "Array" should be general.

**Comment by NPellet** [comment]
``` { length: 3 } ``` would fail @targos test.
@lpatiny's polyfill is the right one, I'm afraid... I guess you guys really need this ? I'm not a fan of this fix.
Thoughts, @targos ?

**Comment by targos** [comment]
@NPellet yes I know, we actually found @lpatiny's version very recently.

**Comment by NPellet** [comment]
Yes it's the polyfill suggested on MDN as well.
Ok then I release 1.12.4-2



2015-07-24 13:28 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by targos** [comment]
OK thanks, can you post the MDN link for reference ?
