### ISSUE TITLE
Error on serie.setData

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#41]
```
TypeError: Cannot read property 'firstChild' of undefined
    at build../series/graph.serie.line.$.extend.empty (http://localhost:63342/visualizer/src/components/jsgraph/dist/jsgraph.js:8237:32)
    at build../graph._serie.$.extend.setData (http://localhost:63342/visualizer/src/components/jsgraph/dist/jsgraph.js:2973:12)
```

**Comment by NPellet** [comment]
Critical ?

Le vendredi 10 juillet 2015, Michaël Zasso <notifications@github.com> a
écrit :

**Comment by NPellet** [comment]
Ah shit. Can you fix it and make a PR if it's needed urgently ? I'm in
vacation without my computer

**Comment by targos** [comment]
ok I'll try to fix it

**Comment by targos** [comment]
Bug was introduced by this line https://github.com/NPellet/jsGraph/blob/master/src/graph._serie.js#L58
The empty method is trying to access `this.groupMarkers` which is undefined.
I don't know if it should be removed or if the groupMarkers should be present

**Comment by NPellet** [comment]
For now just add a condition to check if it is present or not in the empty
method

Le samedi 11 juillet 2015, Michaël Zasso <notifications@github.com> a
écrit :

**Comment by NPellet** [comment]
Thx for the help.
