### ISSUE TITLE
Continuous testing

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#42]
I added some dependencies to enable continuous testing using travis.

To simulate a browser environment, I am using jsdom. This library is only compatible with iojs so you need to install it instead of node in order to run the tests.

To build the dist files and run the test suite: `npm test`
To run the test suite: `npm run test-mocha`

The test files must be located in `test/node`.
The current test I created is failing because of #41.

Only @NPellet can enable the travis hook on https://travis-ci.org/

**Comment by NPellet** [comment]
Looks nice. Will check it out when I come back

Le samedi 11 juillet 2015, Michaël Zasso <notifications@github.com> a
écrit :

**Comment by NPellet** [comment]
Quite cool.

I'll come back if I have questions :)

**Comment by NPellet** [comment]
https://travis-ci.org/NPellet/jsGraph/builds/72425830

What do you think ?

**Comment by targos** [comment]
Just a typo in https://github.com/NPellet/jsGraph/blob/master/src/plugins/graph.plugin.selectScatter.js#L1
Should be `../dependencies/eventEmitter/EventEmitter`. It works on OSX because the file system is case-insensitive

**Comment by NPellet** [comment]
Thank you :)

2015-07-24 10:30 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by NPellet** [comment]
@targos, can you check the problem with Travis CI in the latest release ?
