### ISSUE TITLE
error with plugin selectScatter

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#44]
In graph options:
```js
options.plugins['selectScatter'] = {};
options.pluginAction['selectScatter'] = {
    shift: false,
    ctrl: false
};
```

During serie creation:
```js
var plugin = this.graph.getPlugin( 'selectScatter' )
plugin.setSerie( serie );

plugin.on( 'selectionProcess', function( selectedIndices ) {
    console.log(selectedIndices);
} );

plugin.on( 'selectionEnd', function( selectedIndices ) {
    console.log('end', selectedIndices);
} );
```

Error: `Plugin "selectScatter" has not been loaded or properly registered`

**Comment by NPellet** [comment]
I didn't know this plugin was in use...

**Comment by NPellet** [comment]
In 1.12.4.3 I don't have this issue, but I did not actively fix it

**Comment by targos** [comment]
It is not in use yet, I am trying to implement the feature :wink:

**Comment by NPellet** [comment]
Cool !
But let me know, I can't reproduce this bug right now.

**Comment by targos** [comment]
alright I'll try again tomorrow

**Comment by targos** [comment]
So it works correctly but only with `{shift: false, ctrl: false}`;
I need it to work with the CTRL key in the spectra displayer, because no key is for zoom and shift is for drag

**Comment by NPellet** [comment]
Ok but it gives the same error as you have reported ?

2015-07-29 12:01 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by targos** [comment]
no the error is gone. nothing is happening in fact, like if the plugin was not activated

**Comment by NPellet** [comment]
Hmm I can't reproduce your behaviour

With  v1.12.4-9, I used 

```
var graphinstance = new Graph( domGraph, {

			plugins: {
				'selectScatter': {},
			},

			pluginAction: {
				'selectScatter': { shift: false, ctrl: false, alt: true }
			}
		} );

		var serie = graphinstance.newSerie("serieTest", { }, 'scatter')
			.setLabel( "My serie" )
			.autoAxis()
			.setData( series[ 0 ] )
			.setStyle( 
				{ shape: 'circle', r: 2, fill: 'rgba(255, 0, 0, 0.3)', stroke: 'rgb(255, 100, 1)' }
			)
			.setStyle(
				{
					fill: 'rgba(40, 150, 20, 0.3)',
					stroke: 'rgba( 40, 150, 20, 1)',
					r: 2
				},

				'selected'
			);

		var plugin = graphinstance.getPlugin('selectScatter');
		plugin.setSerie( serie );

		plugin.on('selectionProcess', function( selectedIndices ) {
			selectedDom.html( "Selected number: " + selectedIndices.length + "<br />Selected indices: " + selectedIndices.join(", ") );
		} );

		plugin.on('selectionEnd', function( selectedIndices ) {
			selectedDom.html( "Selection has ended. Number of selection: " + selectedIndices.length );		
		} );
	
		graphinstance.redraw( );
		graphinstance.drawSeries();	

		
```

And it works fine.

Are you sure that with your computer settings, ctrl + click sets e.ctrlKey to true ?

**Comment by targos** [comment]
you are right, it works well with `{ shift: false, ctrl: false, alt: true }` but not with `{ shift: false, ctrl: true }`.

In fact when I click with the ctrl key pressed, it never enters in the event handler (same with meta key)

**Comment by NPellet** [comment]
What do you think ? Is it a browser thing ?

For me Ctrl + Click enables the context menu. However I don't know what
happens if I prevent it from appearing

2015-07-30 16:33 GMT+02:00 Michaël Zasso <notifications@github.com>:
