### ISSUE TITLE
markers do not have "highlight" anymore

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#45]
I think it is since v1.12.
Before, passing over a marker would add a square around it, and clicking on it would make the square stay until you click again. This behavior seems to have disappeared

**Comment by targos** [comment]
cross-ref: https://github.com/NPellet/visualizer/issues/477

**Comment by NPellet** [comment]
Oups... Looking into it right now

**Comment by NPellet** [comment]
Ok with 1.12.4-4

**Comment by targos** [comment]
perfect, thanks!
