### ISSUE TITLE
Zoom in discrete data fails

### ISSUE THREAD

**Issue by andcastillo** [NPellet/jsGraph#47]
If you try to zoom the peaks between 3-5 ppm in the second module, it does not show the peaks. Also, if you zoom any part of the baseline it does not shows anything. 
[example]
(http://www.lactame.com/visualizer/v2.26.1/index.html?viewURL=http://visualizer.epfl.ch/x/XRvxnbdKGzK6UAk6plhj/view.json&dataURL=http://visualizer.epfl.ch/x/XRvxnbdKGzK6UAk6plhj/data.json)

**Comment by NPellet** [comment]
Thank you indeed that was a 0 issue. I released a fix, you can ask Michael to push it.
