### ISSUE TITLE
Time axis problem

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#48]
Testcase: http://direct.lactame.com/visualizer/HEAD/index.html?viewURL=http://visualizer.epfl.ch/x/YgLYvZoe0EmIfHuIqJdd/view.json&dataURL=http://visualizer.epfl.ch/x/YgLYvZoe0EmIfHuIqJdd/data.json

We get a SyntaxError (invalid date)

Data: 
```js
[
  1436911200000,
  1,
  1434664800000,
  1,
  1427238000000,
  1,
  1412373600000,
  1,
  1346450400000,
  1,
  1399672800000,
  1,
  1365199200000,
  1,
  1433628000000,
  1,
  1394924400000,
  1,
  1407967200000,
  1,
  1342476000000,
  1,
  1424905200000,
  1,
  1433196000000,
  1,
  1382824800000,
  1,
  1395788400000,
  1,
  1436997600000,
  1,
  1374530400000,
  1,
  1383433200000,
  1,
  1386370800000,
  1,
  1376085600000,
  1,
  1432072800000,
  1,
  1341266400000,
  1,
  1384642800000,
  1,
  1337551200000,
  1,
  1392937200000,
  1,
  1357340400000,
  1,
  1364767200000,
  1,
  1397685600000,
  1,
  1306620000000,
  1,
  1386284400000,
  1,
  1396216800000,
  1,
  1378850400000,
  1,
  1381960800000,
  1,
  1355698800000,
  1,
  1423350000000,
  1,
  1407189600000,
  1,
  1374357600000,
  1,
  1432591200000,
  1,
  1406152800000,
  1,
  1403042400000,
  1,
  1331679600000,
  1,
  1433023200000,
  2,
  1382914800000,
  2,
  1435010400000,
  3,
  1437516000000,
  3,
  1383951600000,
  3,
  1406498400000,
  4,
  1436047200000,
  5
]
```

**Comment by targos** [comment]
Cross-ref: https://github.com/NPellet/visualizer/issues/664

**Comment by targos** [comment]
(using v1.12.4-12)

**Comment by NPellet** [comment]
Sorry, can't reproduce the specific SyntaxError.

There was another issue, though: the time axis was not done to handle such a wide range of dates. Fixed and shipped in 1.12.4-14

**Comment by targos** [comment]
I guess v1.12.4-14 has the new draw method, what do we need to know about it ?

**Comment by NPellet** [comment]
It's a clever replacement for graph.draw(); and graph.drawSeries();

You can use it when the data of the series have changed (through
serie.setData()), when you have triggered a zoom on the graph
(axis.zoom(a,b)), or when you have changed the serie style
(lineSerie.setLineColor(), ...). It also replaces the first redraw(), which
will be deprecated in a couple versions, maybe.

There should be barely any performance change as the axes will not be
redrawn if their boundaries haven't changed. Similarly, the serie will not
be redrawn if its data hasn't changed. So I guess you should actually see
performance improvements if you called .drawSeries() when it wasn't
required.


2015-08-03 11:04 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by NPellet** [comment]
The feature has been tested internally, but well... it's difficult to have full coverage on this one. Let me know if you see any bug.

**Comment by targos** [comment]
OK thank you

**Comment by NPellet** [comment]
If you want to change the style of the serie externally

``` serie.styles['unselected'].lineColor = 'red' ```

then you can call

```serie.styleHasChanged();```

which will be taken into account the next time you call ```graph.draw();```
and the line color will then only be updated.

**Comment by targos** [comment]
I still have this invalid date error btw

**Comment by targos** [comment]
You don't see it in the console with the testcase above ?

**Comment by NPellet** [comment]
No I really don't see it...

**Comment by NPellet** [comment]
Can you do a jsBin ?

**Comment by targos** [comment]
I can try

**Comment by targos** [comment]
I couldn't find the problem, but recreating the graph module from scratch fixed it. I'll close this issue and reopen if it happens again
