### ISSUE TITLE
2d XY array: problem with first point

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#49]
see http://direct.lactame.com/visualizer/HEAD/index.html?viewURL=http://visualizer.epfl.ch/x/RTnmi0UPaPu004hqsJlZ/view.json&dataURL=http://visualizer.epfl.ch/x/RTnmi0UPaPu004hqsJlZ/data.json

The first data point is drawn at 0 but it should be 0.20172022811706417

**Comment by NPellet** [comment]
Yes I've seen that issue recently... Will look into it now

**Comment by NPellet** [comment]
Cannot reproduce this result... My first point is at 0.2017...

**Comment by NPellet** [comment]
Ah ! Check your x axis. It's not 0, it's 0.2017...

**Comment by targos** [comment]
Ah yes ! Just need to force minY...
Sorry about that

**Comment by NPellet** [comment]
The issue would be to force 0 in case of a ```lineToZero: true```. But this would be a wontfix in fact.
Not only because the API provides axis.forceMin( 0 ), but also because it would be difficult to implement it.
Besides, I'm not sure this is the behaviour in every case.

**Comment by targos** [comment]
No it's fine, I don't like when the system is too permissive and fixes mistakes without telling you. We need to use forceMin, that's not a big deal

**Comment by NPellet** [comment]
Is it in reference with other changes I made :) ?

**Comment by targos** [comment]
No, it was just a general thought :laughing:
