### ISSUE TITLE
API changes

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#52]
While updating to the latest version, I encountered some changes in the API.
Just asking here if I picked the correct new methods:

* `axis.togglePrimary/SecondaryGrid` :arrow_right: `axis.setPrimary/SecondaryGrid`
* `axis.getActualMin/Max` :arrow_right: `axis.getCurrentMin/Max`

**Comment by targos** [comment]
Also are there other changes I may not have seen ?

**Comment by NPellet** [comment]
Yes you picked the right ones. Sorry I didn't let you know.
I deprecated some methods, but I don't think there's anything major besides
what you pointed out.
However more changes will come in a (maybe) close future.


2015-08-28 13:16 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by targos** [comment]
OK, thank you
