### ISSUE TITLE
Zoom bug

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#54]
jsbin: http://jsbin.com/wulonoloye/edit?html,js,output

When you click on the zoom button, axes are being resized correctly but not the serie. Only the second half of it is displayed.

**Comment by NPellet** [comment]
Ok thank you. Will be fixed tonight

2015-09-09 13:48 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by NPellet** [comment]
Ok that's fixed and shipped in v1.13.3-17
Your example was another edge case. Hope there are not so many more.

**Comment by targos** [comment]
Thank you
