### ISSUE TITLE
Time axis

### ISSUE THREAD

**Issue by stropitek** [NPellet/jsGraph#55]
@NPellet , can you have a look at NPellet/visualizer#718

**Comment by stropitek** [comment]
An example without the visualizer. It is based on the jsgraph documentation example.

http://jsbin.com/yujuse/edit?html,js,output

Two other things: 
* you cannot draw grids on the x axis when using the time axis.
* When zooming in the time axis does not correspond to what was selected

**Comment by targos** [comment]
http://jsbin.com/fezojeyeki/edit?js,output

**Comment by targos** [comment]
fixed by 1cba20a28e142e2ec93f7e946cbbef8522f88f65
