### ISSUE TITLE
Zoom problem

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#58]
If the page is scrolled, zoom is shifted from the cursor.

![jsgraph-zoom](https://cloud.githubusercontent.com/assets/2352663/11325499/d870b836-914f-11e5-9b8f-5a7f07d4ca77.gif)

**Comment by targos** [comment]
This is with the latest release

**Comment by NPellet** [comment]
Argh I fucked up. Thanks

2015-11-22 19:33 GMT+01:00 Michaël Zasso <notifications@github.com>:

**Comment by targos** [comment]
https://www.youtube.com/watch?v=eIZKqVFaoB4

**Comment by NPellet** [comment]
Yeah kind of :D

2015-11-22 19:57 GMT+01:00 Michaël Zasso <notifications@github.com>:

**Comment by NPellet** [comment]
Ok try it with 1.13.3-28

**Comment by targos** [comment]
It works now, thanks
