### ISSUE TITLE
Markers may disappear after zooming

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#59]
![jsgraph-zoom2](https://cloud.githubusercontent.com/assets/2352663/11332132/3cf0a0dc-91c3-11e5-93a6-c54203e86b8d.gif)

**Comment by NPellet** [comment]
Oh :(

I see.

**Comment by targos** [comment]
Are you able to fix this today ?
We have memory leaks with the version used in the visualizer and would like to update

**Comment by NPellet** [comment]
Well it's kind of midnight here :)

I can check tomorrow.

Enjoy colombia.

2015-12-01 20:26 GMT+01:00 Michaël Zasso <notifications@github.com>:

**Comment by NPellet** [comment]
Ok can you check ?
I think it's fine now

**Comment by targos** [comment]
Looks good, thanks!

**Comment by NPellet** [comment]
Cool !

2015-12-02 16:54 GMT+01:00 Michaël Zasso <notifications@github.com>:
