### ISSUE TITLE
Zone serie doesn't work when there is a legend

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#60]
Testcase: http://visualizer.epfl.ch/tiny/5FO5Nv7FuuQkWNSadaWN

**Comment by NPellet** [comment]
Ok thanks for the report. Will be fixed this afternoon.

**Comment by NPellet** [comment]
Fixed in 1.13.3-31

**Comment by NPellet** [comment]
Can you valide @targos ? (Maybe after the Solar Decathlon :D)

**Comment by NPellet** [comment]
( Also you might want to check out the .autoPosition(left|right|bottom|top) in 1.13.3-33 )

**Comment by targos** [comment]
I will validate when I m back in Switzerland

**Comment by NPellet** [comment]
If you're interested, I also released speed persistance and deceleration in
the drag plugin in v1.13.3-34 (Apple style).

Maybe useful to show time data...

2015-12-12 19:05 GMT+01:00 Michaël Zasso <notifications@github.com>:
