### ISSUE TITLE
Error when calling the resize method

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#61]
I'm trying to include the latest (1.13.3-35) release in the visualizer and have the following error:
![image](https://cloud.githubusercontent.com/assets/2352663/11780680/1c482100-a264-11e5-9f73-e669d3c43897.png)

**Comment by NPellet** [comment]
Ok I let you check the latest version :)

**Comment by targos** [comment]
Actually there is still a problem with the grid.
Whatever I set for primary and secondary grid, the graph is being drawn with a horizontal grid

**Comment by targos** [comment]
http://direct.lactame.com/visualizer/HEAD/?viewURL=http://visualizer.epfl.ch/x/5FO5Nv7FuuQkWNSadaWN/view.json&dataURL=http://visualizer.epfl.ch/x/5FO5Nv7FuuQkWNSadaWN/data.json

**Comment by NPellet** [comment]
ok will check

2015-12-17 10:12 GMT+01:00 Michaël Zasso <notifications@github.com>:

**Comment by NPellet** [comment]
How about now ?

**Comment by targos** [comment]
Fixed with the latest release, thanks!
