### ISSUE TITLE
X ticks to sparse ?

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#63]
![image](https://cloud.githubusercontent.com/assets/1484241/12297440/82d07768-ba0d-11e5-84cd-c513b975a42e.png)

In some case there are not enough labels on the X axis I find but this is a special case where the first value is just after 0.

**Comment by NPellet** [comment]
Yes so like as said (for the record), I need to specify a number of primary tick as a function of total graph dimension, not just in total.

In addition, might be a good idea to ensure no clashes, but that's for another time.
