### ISSUE TITLE
broken links on jsgraph.org and broken examples

### ISSUE THREAD

**Issue by Di3g0** [NPellet/jsGraph#66]
this page doesn't exist any more
[markers.js](http://www.jsgraph.org/examples/seriestyles/markers.js/)

console return: Uncaught TypeError: Cannot read property 'setAttribute' of undefined
[pluginsandshape.js](http://www.jsgraph.org/examples/plugins/pluginsandshape.js/)

No shape visible
[shapeplugin.js](http://www.jsgraph.org/examples/shapes/shapeplugin.js/)

console return: Uncaught TypeError: Cannot read property 'setAttribute' of undefined
[lockshape.js](http://www.jsgraph.org/examples/shapes/lockshape.js/)

Tested Browser: 
Google-Chrome 48.0.2564.82 (64-bit)
Firefox 43.0.4 (64-bit)

**Comment by NPellet** [comment]
Hey, thanks for reminding me :)

Actually the website is not up to date at all. I've been working on a new one for a while but it takes some time.
All this documentation is accessible in the /doc folder of the repo. There are a couple tutorials that are worth checking out.

Thanks anyway !

**Comment by Di3g0** [comment]
thank you to :)
