### ISSUE TITLE
Relative text annotations

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#67]
I can not let work labels that has relative position compare to the annotations. The absolute position works, the dx position works IF x is specified but does not if x is not specified. I would expect that by default "x" is the value of the annotation and the position of the text is relative to the annotation.

Something like:
```
{
    "fillColor": "rgba(0,255,0,50)",
    "type": "rect",
    "strokeColor": "blue",
    "strokeWidth": "3px",
    "position": [
      {
        "y": "0px",
        "x": 260.1
      },
      {
        "y": "10px",
        "x": 260.2
      }
    ],
    "labels": [
      {
        "text": "Label1",
        "position": {
          "x": "150px",
          "y": "150px"
        }
      },
      {
        "text": "Label2",
        "position": {
          "dx": "50px",
          "y": "150px"
        }
      },
      {
        "text": "Label3",
        "position": {
          "dx": 1,
          "dy": 0
        }
      },
      {
        "text": "Label4",
        "position": {
          "x": 260,
          "y": 0.5,
          "dx": 1
        }
      }
    ]
  }
```

**Comment by NPellet** [comment]
Check the doc. API has changed.

Call

shape.getPosition( 0 ).relativeTo( shape.getPosition( 1 ) ); for example.

2016-01-27 10:11 GMT+01:00 lpatiny <notifications@github.com>:

**Comment by NPellet** [comment]
Ah actually your question is a bit more complicated. I'll look into it.

2016-01-27 10:31 GMT+01:00 Norman Pellet <norman.pellet@gmail.com>:

**Comment by NPellet** [comment]
Ah yes that's what I meant actually. You need to call something like

```shape.getLabelPosition().relativeTo( shape.getPosition( 0 ) )```

I will see if I can make something work through the configuration JSON rather than the API...

**Comment by lpatiny** [comment]
Please try to do something indeed because it would really be complex to use the API for this purpose while everything is currently stored in the JSON
