### ISSUE TITLE
Vertical scale with bar graph

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#68]
With a bar graph when you make a vertical scale and the top of the peak is not displayed anymore, the peak disappear

https://www.lactame.com/visualizer/load.html?viewURL=https://visualizer.epfl.ch/x/O5AiY10aAwZFL5BCHnAw/view.json&dataURL=https://visualizer.epfl.ch/x/O5AiY10aAwZFL5BCHnAw/data.json

https://github.com/NPellet/visualizer/issues/834

**Comment by targos** [comment]
looks like it is done on purpose: https://github.com/NPellet/jsGraph/blob/master/src/series/graph.serie.line.js#L747-L753

cc @NPellet

**Comment by NPellet** [comment]
No the line of code you are referring to is legit, it's only to prevent
drawing for x that are not covered.

So the bug is valid, the point should indeed display. I'll dig further

2016-03-11 10:35 GMT+01:00 Michaël Zasso <notifications@github.com>:

**Comment by targos** [comment]
It's fixed now, thanks !
