### ISSUE TITLE
new data format ?

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#70]
Would it make sense to allow the data to send as an object of x, y, dx, dy, ...

```
{
  x: [x1, x2, ...],
  y: [y1, y2, ...],
  dx: [...], // we could also add error bars directly in the data
  dy: [...]
}
```

**Comment by NPellet** [comment]
Yes not so bad. Problem is, dx can be separated in positive and negative
values, and also in different levels (bar, box, 1sigma, 3 sigma, ...)

2016-03-14 14:24 GMT+01:00 lpatiny <notifications@github.com>:

**Comment by lpatiny** [comment]
Yes I new it, this is why I left "..." for the format. But I was mainly for the idea of object that would make on our side things much easier. For error bars I guess you could multiply the number of array

- dxUnder
- dxOver
- dx...

**Comment by NPellet** [comment]
So basically your only proposed modification is to add errors directly ? I have no problem with that...

**Comment by targos** [comment]
The main point is to add support for `{x: [], y: []}`

**Comment by NPellet** [comment]
Oh... jsGraph doesn't support it ? I see... I'll look it up

**Comment by NPellet** [comment]
But it seems to me that this data format is supported...

```
   if ( data[ 0 ].x ) {

        for ( var i = 0, l = data.length; i < l; i++ ) {

          var arr = this._addData( type, data[ i ].x.length * 2 );
          datas.push( arr );

          z = 0;
          for ( var j = 0, m = data[ 0 ].x.length; j < m; j++ ) { // Several piece of data together
            arr[ z ] = ( data[ i ].x[ j ] );
            z++;
            arr[ z ] = ( data[ i ].y[ j ] );
            z++;
            this._checkX( data[ i ].x[ j ] );
            this._checkY( data[ i ].y[ j ] );
            total++;
          }
        }

      }
```

**Comment by NPellet** [comment]
Oh, ok, obviously this code won't work :D.
