### ISSUE TITLE
if a serie is unselected, all the axes should be selected

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#73]

**Comment by NPellet** [comment]
Axed can not be selected...

**Comment by NPellet** [comment]
Can you comment ?

**Comment by targos** [comment]
this is related to #72. We think that if all series have been unselected, it should behave like when the graph is first loaded: zoom applies to all axes.

**Comment by targos** [comment]
It seems to work correctly only if the legend options are set to `{isSerieHideable: false, isSerieSelectable: true}`.
If `isSerieHideable` is true, it is still selected after reappearing.

**Comment by NPellet** [comment]
Yeah ok but #72 is fixed I think.

As for the legend, I'd like you or Luc to propose a better way to do. This is not ideal in the current form.
