### ISSUE TITLE
Possibility to save / load status ?

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#74]
When we superimpose the charts and scale / zoom them it would be nice to be able to save the current state.

In hook we had the program when pressing a number it would save the current zoom information and if we press again the same number it would recall the previously saved information.
This could be done outside jsGraph if jsGraph give the possibility to have a "getView" and "putView" that would allow to save the current state and reload it.

**Comment by NPellet** [comment]
only the zoom ?

**Comment by stropitek** [comment]
Well the "pan" and "zoom" of each axe.
Now indeed the visibility of each serie would also be important to save.

On the other end Color, shape, ... does not seems important to save because we would likely not change them.

You are thinking about something else ?

**Comment by NPellet** [comment]
No no, I was just not sure exactly what you were trying to achieve. The
axis from / to would be easy to save.

But there are a lot of options you can set by the API, and maybe I should
also extract them at the same time. Not sure.

2016-05-11 9:24 GMT+02:00 Daniel Kostro <notifications@github.com>:

**Comment by NPellet** [comment]
```

		var state = graphinstance.getAxisState();
		state.left[ 0 ] = [ 10, 20 ];
		graphinstance.setAxisState( state );

```
