### ISSUE TITLE
Possibility to zoom out ?

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#75]
Is there a possibility to zoom out ?

Would be nice to have a way to zoom out by a factor 2 for example. We could assign this function to a shift+click while shift+drag would allow to drag the spectrum (exact keys may change depending the application).

**Comment by NPellet** [comment]
There is one actually: 

```

      if ( pref.mode == 'gradualX' ||  pref.mode == 'gradual' ) {

        this.toAxes( function( axis ) {

          axis._pluginZoomMin = axis.getCurrentMin();
          axis._pluginZoomMax = axis.getCurrentMax();

          axis._pluginZoomMinFinal = axis.getCurrentMin() - ( axis.getCurrentMax() - axis.getCurrentMin() );
          axis._pluginZoomMaxFinal = axis.getCurrentMax() + ( axis.getCurrentMax() - axis.getCurrentMin() );

        }, false, true, false );

        modeX = true;

      }

      if ( pref.mode == 'gradualY' ||  pref.mode == 'gradual' ) {


```

That's the mode of the zoom plugin

**Comment by lpatiny** [comment]
@targos We could add an option in the spectraDisplayer that if you make shift+click you do the zoom out based on the drag zoom preferences ?
This means that if drag zoom is X, only X, if XY, both axes.

**Comment by NPellet** [comment]
I'm closing that in the meantime
