### ISSUE TITLE
resizing the graph only redraws axes

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#77]
The series are left as is and `graph.draw()` does not have any effect.
http://jsbin.com/gahuyinewu/edit?html,js,output

**Comment by NPellet** [comment]
Noted

**Comment by NPellet** [comment]
@targos can you try with the latest version ?

**Comment by targos** [comment]
Doesn't seem to be fixed: http://jsbin.com/vudoqowoxi/1/edit?html,js,output

**Comment by NPellet** [comment]
Ok now it's fixed.

2016-06-02 14:02 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by targos** [comment]
Indeed. Thanks!
