### ISSUE TITLE
Text of peak picking labels seems empty

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#78]
In the view:

https://visualizer.epfl.ch/tiny/sgLokO3QydNg1W8p1xbA

When we click on the label "1.111" the text of the label is empty. I would expect it to be 1.111

![image](https://cloud.githubusercontent.com/assets/1484241/15538123/835be7dc-227a-11e6-869f-dae85ec509b2.png)

![image](https://cloud.githubusercontent.com/assets/1484241/15538125/878b987a-227a-11e6-9be9-4b3238f9cc99.png)

**Comment by NPellet** [comment]
Because you're not extracting the right data.

Using .getProperties rather than reading the object. You'll see the true structure of your object
