### ISSUE TITLE
color spectra

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#79]
When you have 1000 different spectra you can make an average of them to create a new spectrum that you would like to display. Each point of this new spectrum has a specific variance and in some cases (metabolomics) this is an important value.

It would be nice that you can choose for each segment of a line the color of it. This means having as data:
x: []
y: []
color: []

Do you think  it would be easy to implement ? Also realated to the possibility to directly send an object with x, y, color to jsgraph ?

**Comment by NPellet** [comment]
Well it can be implemented, but forget about speed in this case. Imagine
the number of nodes this would create...

Are you ready to accept that ?

2016-05-26 11:34 GMT+02:00 lpatiny <notifications@github.com>:

**Comment by lpatiny** [comment]
Well we will see about speed ... we are looking to 128 k points ...

**Comment by NPellet** [comment]
Can be faster if I bundle the colors together. How many would you expect ?

2016-05-26 17:07 GMT+02:00 lpatiny <notifications@github.com>:

**Comment by lpatiny** [comment]
It will be kind of continuous coloring ... each point has a deviation and we will calculate the color based on HSL model (changing the angle). Now indeed we could think that 360 colors would be in general the maximum.

**Comment by NPellet** [comment]
Ok but so we're talking about the lines between two points, right ? Do you
have maybe an example ?

2016-05-26 17:15 GMT+02:00 lpatiny <notifications@github.com>:

**Comment by targos** [comment]
we would like to be able to plot something like this: http://www.gnuplotting.org/figs/sweep-66590.png

**Comment by NPellet** [comment]
Ah ok got it. Using the line as a the clipping element of the gradient
isn't an option ?

i.e. is the gradient monotoneous ?

2016-05-26 17:26 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by lpatiny** [comment]
Here is the kind of image

![image](https://cloud.githubusercontent.com/assets/1484241/15601906/71ad5cae-23f2-11e6-9eaf-2408d5b129e5.png)

From the paper: http://www.mdpi.com/2218-1989/2/3/479

The color depends on information that are not related to X / Y. The gradient is not monotoneous.

**Comment by NPellet** [comment]
I see.

I have to think about it so that it doesn't hurt speed too much

2016-05-27 10:05 GMT+02:00 lpatiny <notifications@github.com>:

**Comment by NPellet** [comment]
Check latest release. Code example is in 10-basic/test3

**Comment by targos** [comment]
Thanks. @NPellet could you commit the missing source file ?
`src/series/graph.serie.line.colored.js`

**Comment by NPellet** [comment]
Oups. Done

2016-05-27 17:04 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by targos** [comment]
I see that the code expects a 2D array for the colors and it's not obvious how we should define it. Could you elaborate ?
The code example is still unavailable btw.

**Comment by NPellet** [comment]
Well it's just that the data array should also be 2D array. It's used for
piecewise functions, with gaps between different data sets. But there's a
fudge in the .setData that allows a 1D array too.

The same fudge simply wasn't done for colors. If you're not using piecewise
functions, you can simple define the colors in the first element of the
array. [ [ c1, c2, c3, ... ] ]

**Comment by NPellet** [comment]
@targos, @lpatiny 
When you guys have a nice example to show, can I have an example to put in the example list ?
