### ISSUE TITLE
Click and double click events

### ISSUE THREAD

**Issue by andcastillo** [NPellet/jsGraph#80]
There are 2 problems with the current click management:
1. If you click over the legend of the spectrum(or anywhere under the x axe) it fires and event as if you clicks over the spectrum area. I think that event should be fired only if you click over the the axe.
2. If you double click,  jsGraph fires 2 click events. Is it possible not to fire the click event in such case or to have an alternative modified action for the click(shift+click)?

**Comment by NPellet** [comment]
Ok changed point 1, but if someone complains, I'll change it back.
Point 2 is a javascript thing. The click events are always fired, which is why there's a debouncing

**Comment by NPellet** [comment]
Ah no, there was a debounce, I removed it.

You can use graph.prevent( true ); to prevent the click event to be used.

**Comment by targos** [comment]
> You can use graph.prevent( true ); to prevent the click event to be used.

Where exactly ? I tried in the event callback without success

**Comment by andcastillo** [comment]
Problem 1 is partially solved. Event on the legend area still changing the zoom, only once, after you double click on the spectrum(full zoom out)

**Comment by NPellet** [comment]
Fixed and tested in the latest ES6 commit.
