### ISSUE TITLE
expected behaviour ?

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#81]
I'm currently superimposing NMR spectra that has a big spike in the middle. Meaning the baseline is at 0 but if you want to display the full spectrum the 0 is rather in the middle of the screen while it should be more in the bottom.

You may force the minY to 0 in order to put the baseline at 0 but there is a little bit of noise that you would still like to see.
For normal spectra (without spikes) I just put a "spacing under" of 5% and in works perfectly. However if minY is forces to 0, the space under is completely ignored and I don't know if this is the expected behaviour. What I would expect is that the 0 is at 5% high.

**Comment by NPellet** [comment]
Example ?

2016-06-03 11:21 GMT+02:00 lpatiny <notifications@github.com>:

**Comment by NPellet** [comment]
Ah no, forced value is a forced value, and ignores the dataSpacing option. This is expected behaviour.
