### ISSUE TITLE
support the 'chart' json format

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#86]
https://docs.google.com/document/d/15gZgpxApRYjCFqbE95DITqAcrOW8bEEbPcXnTcRNzgY/edit?usp=sharing

The format can still be improved for dx, dy, style, ,,, but it would be nice that most of the features are accessible directly from a simple json.

This would allow to easily generate chart in an automatic way. By specifying min / max value for axes we can also generate automatically reports with enlargement of zones that were determine grammatically.

This is already supported by the visualizer as a 'type renderer'
https://github.com/NPellet/visualizer/blob/master/src/src/util/typerenderer/chart.js
but it would make this code much smaller !

**Comment by targos** [comment]
The google doc you linked to is outdated. We have a repo with the latest JSON structure definition for charts

**Comment by lpatiny** [comment]
OK here is the link

https://github.com/cheminfo/json-chart/blob/master/chart-schema.json

**Comment by NPellet** [comment]
Can I make pull requests on that ?

2016-06-11 8:57 GMT+02:00 lpatiny <notifications@github.com>:

**Comment by lpatiny** [comment]
Yes sure
