### ISSUE TITLE
show label INCLUDING the limits ?

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#87]
Currently it seems that when we force the x value from 0 to 100 the labels for  100 is not displayed. 
I think it would look nicer and be more logical to display the last label if it is exactly the same value.

Today we need to put 100.00000001 in order to display this label.

****
![image](https://cloud.githubusercontent.com/assets/1484241/16071540/40e096f6-32dc-11e6-95cf-e8df616420f1.png)

**Comment by lpatiny** [comment]
Same is true for the grid line.

**Comment by NPellet** [comment]
You can try with v1.14.4-1

**Comment by targos** [comment]
It's fine, thanks
