### ISSUE TITLE
Catch event on the legend after full zoom out

### ISSUE THREAD

**Issue by lpatiny** [NPellet/jsGraph#89]
The events are correctly catch on the legend when you load a spectrum on zoom in it.

However after a double click (full zoom out) the legend does not catch the events anymore.

**Comment by targos** [comment]
this issue is still present on latest version

**Comment by NPellet** [comment]
Hmmm...
I have to investigate.

```
      this.svg.addEventListener( 'click', function( e ) {
        e.stopPropagation();
      } );
      this.svg.addEventListener( 'dblclick', function( e ) {
        e.stopPropagation();
      } );
```

2016-07-01 10:54 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by lpatiny** [comment]
Actually this bug is still present. We can easily reproduce it in the view:

http://www.cheminfo.org/Spectra/Mass/MF_from_monoisotopic_mass/index.html?viewURL=https%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo-public%2F4a06cbbc25197036518fab2ea6ff961d%2Fview.json%3Frev%3D53-4a1ed943d61b8823c7cda0c1c5be8ac7&dataURL=https%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo-public%2F4a06cbbc25197036518fab2ea6ff961d%2Fdata.json%3Frev%3D53-4a1ed943d61b8823c7cda0c1c5be8ac7

Click on a mass, zoom in a peak, double click to zoom out.

Click in the legend but not on the label of a spectrum. It will zoom in.

**Comment by NPellet** [comment]
Actually it's more general. Double click then click anywhere else that's
not on the drawing zone. It will zoom

Noted.

2016-09-30 12:22 GMT+02:00 Luc Patiny <notifications@github.com>:
