### ISSUE TITLE
remove dependency on jquery

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#91]
@NPellet would you accept such a change ?

The code is mainly using `$.extend` and a few methods that are easy to copy over.

**Comment by NPellet** [comment]
Yes I would love to remove it completely.

I remember something other than $.extend, though.

Can you take care of the $.extend ? There's already an util.extend but it makes arrays into object I think...

**Comment by targos** [comment]
OK I'll work on it

**Comment by targos** [comment]
FWIW I'm using this website to translate jquery methods to vanilla JS: http://youmightnotneedjquery.com/

**Comment by NPellet** [comment]
Cool. Did you locate the other potential issues or should I look them up ?

2016-07-06 14:45 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by targos** [comment]
I'll try to change everything and come back to you if there is an issue

**Comment by targos** [comment]
Another website, more complete: http://codeblog.cz/vanilla/

**Comment by targos** [comment]
OK I think everything is migrated. to be tested now

**Comment by NPellet** [comment]
If that works, that's really awesome !

If the methods are taken from a website, can you please leave a reference
as a comment ?

2016-07-06 17:14 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by targos** [comment]
No apparent breakage for the visualizer

**Comment by targos** [comment]
Closing as it seems to be working. We can reopen if a problem arises.
