### ISSUE TITLE
publish on npm

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#92]
I'd like to publish the package on npm. The problem is that the name `jsgraph` and its close variations are already taken.
@NPellet do you have an idea for the name ?
You can search on https://npms.io/search?term=jsgraph to see if it is available or not.

**Comment by targos** [comment]
@lpatiny suggested `jsgraph-npm`

**Comment by NPellet** [comment]
Can't we just get rid of this guy ?

2016-07-07 12:54 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by targos** [comment]
get rid of what ?

**Comment by NPellet** [comment]
of this guy's project :D

2016-07-07 13:20 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by targos** [comment]
Because there are much more packages on npm and it is easier to get all dependencies from the same place.
npm is not only for server stuff. Even jquery stopped their plugin registry and switched to it: http://plugins.jquery.com/

**Comment by targos** [comment]
https://www.npmjs.com/package/node-jsgraph

@NPellet I'd like to add the publish step to a release but I need to give you permission. What is your npm username ?

**Comment by NPellet** [comment]
npellet

2016-07-08 10:58 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by NPellet** [comment]
vpn-254-110:graph normanpellet$ npm install node-jsgraph
npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "node-jsgraph"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ENOSELF

npm ERR! Refusing to install node-jsgraph as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/normanpellet/Documents/Web/graph/npm-debug.log


Any idea ?

**Comment by NPellet** [comment]
Wrong folder, sorry :)
