### ISSUE TITLE
Implement box plots

### ISSUE THREAD

**Issue by NPellet** [NPellet/jsGraph#98]
https://www.leansigmacorporation.com/box-plot-with-minitab/

Should be a new serie with the currently defined axes.

**Comment by targos** [comment]
Do you mean to compute the boxplot values from the data ? We should have all the required functions in https://github.com/mljs/stat (look at the `array.js` file, documentation is incomplete)

**Comment by NPellet** [comment]
No no, just the display

**Comment by NPellet** [comment]
@targos, this Q1, Q2, Q3 and IQR are standard names ? Do you know anything about that ?

**Comment by targos** [comment]
I'm OK with Q1, Q2 and Q3 but I think the end of the whiskers should have a more general name. It's not always the IQR

**Comment by targos** [comment]
There should also be a way to display the outliers

**Comment by NPellet** [comment]
Outliers are not the issue.

But would you define Q2, or rather Q1-Q2 (low end-mean) as an input ?
As for the IQR, any proposition ?


2016-10-10 9:34 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by targos** [comment]
what about just `whiskers: [y1, y2]` ?

**Comment by NPellet** [comment]
LGTM
